
SPACESHIP_VENV_PREFIX="virtualenv is "
SPACESHIP_GIT_STATUS_ADDED="%{$fg[cyan]%} ✈"
SPACESHIP_GIT_STATUS_MODIFIED="%{$fg[yellow]%} ✭"
SPACESHIP_GIT_STATUS_DELETED="%{$fg[red]%} ✗"
SPACESHIP_GIT_STATUS_RENAMED="%{$fg[blue]%} ➦"
SPACESHIP_GIT_STATUS_UNMERGED="%{$fg[magenta]%} ✂"
SPACESHIP_GIT_STATUS_UNTRACKED="%{$fg[grey]%} ✱"
SPACESHIP_GIT_PREFIX="git branch is "
SPACESHIP_DIR_TRUNC=5
