alias rn="cd $DEV_HOME/pepperoni-app-kit"

alias react_web_demo_app="cd $DEV_HOME/react-hello/my-app"
alias etherum="cd ~/Library/Ethereum"
alias etherum_db="etherum; cd geth/chaindata; open . "
alias etherum_wallet="cd ~/Library/Application\ Support/Ethereum\ Wallet"
alias dev_home="cd $DEV_HOME"
alias dh="dev_home"
alias cv_new="dh; cd ohadperry.github.io/cv-new"
alias cv="dh; cd ohadperry.github.io/cv"
alias sc="dh; cd scenario"
alias courses_dir="dh; cd ohad_temp/tasks"
alias ba="dh; cd contracts"
alias oh="cd ~/.oh-my-zsh"
alias bl="dh; how-build-your-own-blockchain"
# alias serverless_demo="dh; cd myBackendAPI"
# alias bd="serverless_demo"
